name: Build, Test, and Publish ASP.NET Core Application

# Trigger when a tag following the "v*.*.*" format is created (semantic versioning)
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env: 
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_VERSION: '8.0.x'

jobs:
  # Linux based builds
  linux-build:
    runs-on: ubuntu-latest
    # Scopes not defined are set to None as long as one scope is manually set here
    permissions:
        contents: read # Allow checkout action to get the repo code
    strategy:
      matrix:
        platform: [linux-arm, linux-arm64, linux-x64]  # Building for ARM32, ARM64, and x64 (renamed to AMD64)

    steps:
        # Copy the repo code from the tag that triggered this action.
      - name: Checkout tag
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore --runtime ${{ matrix.platform }}

      - name: Run code tests
        run: dotnet test --configuration Release --no-build --verbosity normal --runtime ${{ matrix.platform }}

      - name: Publish project as ${{ matrix.platform }}
        shell: bash
        run: |
          # Get the tag name v*.*.* and remove the "v"
          VERSION_NUMBER=$(echo $GITHUB_REF_NAME | sed 's/^v//')

          # Linux only, rename dotnetCore x64 build to it's wellknown name "AMD64" for later use with dockerfile
          BUILD_NAME="${{ matrix.platform }}"
          if [ "$BUILD_NAME" == "linux-x64" ]; then
            BUILD_NAME="linux-amd64"
          fi
          echo "BUILD_NAME=${BUILD_NAME}" >> $GITHUB_ENV  # Set the variable as a environment variable to use inside others steps

          dotnet publish --configuration Release --runtime ${{ matrix.platform }} --self-contained false --no-restore --output ./build/${{ matrix.platform }} /p:Version=$VERSION_NUMBER /p:AssemblyVersion=$VERSION_NUMBER

      - name: Upload ${{ matrix.platform }}-build as a artifact
        uses: actions/upload-artifact@v4
        with:
          # Change the Name to the custom build name
          name: ${{ env.BUILD_NAME }}-build
          path: ./build/${{ matrix.platform }}
          # Only keep the artifact up on github for 1 day
          retention-days: 1

  # Windows based builds
  windows-build:
    runs-on: windows-latest 
    needs: linux-build
    if: success() # Ensure that there was no error during any of the needed jobs
    # Scopes not defined are set to None as long as one scope is manually set here
    permissions:
        contents: read # Allow checkout action to get the repo code
    strategy:
      matrix:
        platform: [win-x64, win-x86]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore --runtime ${{ matrix.platform }}

      - name: Run code tests
        run: dotnet test --configuration Release --no-build --verbosity normal --runtime ${{ matrix.platform }}

      - name: Publish project as ${{ matrix.platform }}
        shell: pwsh
        run: |
          # Get the tag name v*.*.* and remove the "v"
          $VERSION_NUMBER = $env:GITHUB_REF_NAME -replace '^v', ''
          dotnet publish --configuration Release --runtime ${{ matrix.platform }} --self-contained false --no-restore --output ./build/${{ matrix.platform }} /p:Version=$VERSION_NUMBER /p:AssemblyVersion=$VERSION_NUMBER

      - name: Upload ${{ matrix.platform }}-build as a artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: ./build/${{ matrix.platform }}
          # Only keep the artifact up on github for 1 day
          retention-days: 1

  # Build Docker images and Push to GitHub Packages
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: [linux-build, windows-build]
    if: success() 
    permissions:
      contents: read  # Allow checkout action to get the repo code
      packages: write  # Allow pushing to GitHub Packages
      actions: read # Allow to fetch the actions API
    env:
      DOCKER_BUILD_RECORD_UPLOAD: false
      DOCKER_PLATFORMS: "linux/amd64,linux/arm64,linux/arm" # Builds to release to Github Packages. Separated by commas
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install jq to parse JSON responses from GitHub API
      - name: Install jq
        run: |
          sudo apt-get install -y jq

      # Fetch all artifacts and download those that start with "linux-" and end with "build-"
      - name: Download all build artifacts starting with "linux-" and ending with '-build'
        run: |
          echo "Fetching artifact list for the current workflow..."

          # Fetch the list of all artifacts for the current workflow using the GitHub API
          # Only keep linux builds.
          artifacts=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" \
            | jq -r '.artifacts[] | select(.name | startswith("linux-") and endswith("-build")) | .name + "|" + .archive_download_url')

          # Ensure build directory exists
          mkdir -p ./build

          echo "Downloading build artifacts..."
          echo "$artifacts" | while IFS='|' read -r artifactName artifactUrl; do
            # Extract the artifact name from the URL (remove the .zip extension)
            artifactFilePath="./build/$artifactName.zip"

            # Download the artifact
            echo "Downloading $artifactName..."
            curl -L -o "$artifactFilePath" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$artifactUrl"
          done

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Defines global environment variable for docker build
        run: |
          # Get the tag name v*.*.* and remove the "v"
          CURRENT_DOCKER_RELEASE_VERSION_NUMBER=$(echo $GITHUB_REF_NAME | sed 's/^v//')
          CURRENT_DOCKER_RELEASE_VERSION_NUMBER=$(echo "${CURRENT_DOCKER_RELEASE_VERSION_NUMBER}" | tr '[:upper:]' '[:lower:]')
          echo "CURRENT_DOCKER_RELEASE_VERSION_NUMBER=${CURRENT_DOCKER_RELEASE_VERSION_NUMBER}" >> $GITHUB_ENV  # Set the variable as a environment variable

          # Convert repository path to lowercase
          GITHUB_REPOSITORY_LOWERCASE=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "GITHUB_REPOSITORY_LOWERCASE=${GITHUB_REPOSITORY_LOWERCASE}" >> $GITHUB_ENV

      - name: Build and push Docker image for ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true  # Push the image to the registry
          tags: ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}:${{ env.CURRENT_DOCKER_RELEASE_VERSION_NUMBER }} # ghcr.io/repo-owner/repo-name:v?.?.?
          platforms: ${{ env.DOCKER_PLATFORMS }}
          build-args: |
            BUILD_PATH=./build
  # Download the "build" job artifact and prepare them for release
  publish-to-release:
    runs-on: ubuntu-latest
    needs: [linux-build,windows-build]
    if: success() # Ensure that there was no error during the "build" job
    # Scopes not defined are set to None as long as one scope is manually set here
    permissions:
      contents: write # This grant the write permission to the job since gh-release need the permission to edit a release to upload the build files
      actions: read # Allow to fetch the actions API
    steps:
      # Install jq to parse JSON responses from GitHub API
      - name: Install jq
        run: |
          sudo apt-get install -y jq

      # Fetch all artifacts and download those that end with '-build'
      - name: Download all build artifacts ending with '-build'
        run: |
          echo "Fetching artifact list for the current workflow..."

          # Fetch the list of all artifacts for the current workflow using the GitHub API
          # Only keep those ending with -build.
          artifacts=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" \
            | jq -r '.artifacts[] | select(.name | endswith("-build")) | .name + "|" + .archive_download_url')

          # Ensure build directory exists
          mkdir -p ./build

          # Create a checksum file
          echo "Creating SHA256 checksum table..."
          echo "## SHA256 Checksum Table" > release-checksum.md
          echo "This table contains the SHA256 hashes for each binary compiled using GitHub Actions." >> release-checksum.md
          echo "| File Name  | SHA256 |" >> release-checksum.md
          echo "|------------|--------|" >> release-checksum.md

          # Download the build artifacts and generate SHA256 hashes
          echo "Downloading build artifacts..."
          echo "$artifacts" | while IFS='|' read -r artifactName artifactUrl; do
            # Extract the artifact name from the URL (remove the .zip extension)
            artifactFilePath="./build/$artifactName.zip"

            # Download the artifact
            echo "Downloading $artifactName..."
            curl -L -o "$artifactFilePath" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$artifactUrl"

            # Generate the SHA256 hash for the artifact
            artifactSHA256=$(shasum -a 256 "$artifactFilePath" | awk '{ print $1 }')
            # Add the artifact name and checksum to the markdown table
            echo "| \`$artifactName.zip\` | \`$artifactSHA256\` |" >> release-checksum.md
          done

      # Upload zip to the github release
      - name: Publish build to github release
      # Use a pinned hash as a prevention to repojacking, verify changelogs & latest before updating for security
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 #v2.1.0 pinned hash
        with:
          prerelease: false
          files: ./build/*.zip  # Publish all the generated zip files
          append_body: true
          body_path: release-checksum.md